# Generated by Django 4.1.6 on 2023-02-19 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='prfile_picture',
            new_name='profile_picture',
        ),
    ]
